// Verified component inventory. Read from Figma on 2026-10-07 (see docs/stage-1-audit.md).
// The sidebar, catalog, search index and coverage checklist are all generated from this list.
import type { ComponentEntry, FigmaProperty } from './types';

const v = (name: string, values: string, def?: string): FigmaProperty => ({ name, type: 'Variant', values, default: def });
const t = (name: string, def: string): FigmaProperty => ({ name, type: 'Text', values: 'any string', default: def });
const b = (name: string, def: boolean): FigmaProperty => ({ name, type: 'Boolean', values: 'true, false', default: String(def) });
const PENDING = "DRAFT — pending Mary's approval.";
const PUBLISH = 'DRAFT — created with Mary’s approval; pending library publish.';

export const components: ComponentEntry[] = [
  { slug: 'account-card', title: 'AccountCard', category: 'widgets', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, opacityNote: true, related: ['progress-bar', 'button', 'convert-widget'],
    purpose: 'Dark card for one money account: name, balance, transfer limit with progress, two actions.',
    components: [{ name: 'AccountCard', nodeId: '376:1176', variants: 2, properties: [v('appearance', 'iban, wallet')] }] },
  { slug: 'account-details-modal', title: 'AccountDetailsModal', category: 'overlays', status: 'Draft', statusNote: 'DRAFT — created with Mary’s approval (variant B); pending library publish.', docs: 'Composition specification', built: true, related: ['modal-overlay', 'input', 'detail-row', 'iban-table'],
    purpose: 'Modal window with the details of one IBAN account: amount, IBAN in a read-only copy field, owner, currency, status, two actions.',
    components: [{ name: 'AccountDetailsModal', nodeId: '493:6224', variants: 1, properties: [t('title', 'Personal account details'), t('subtitle', 'Lorem ipsum.'), t('amount', '€2 000 000.00'), t('ibanLabel', 'IBAN number')] }] },
  { slug: 'ai-assistant', title: 'AiAssistant', category: 'widgets', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['chip', 'icon-button'],
    purpose: 'AI assistant panel: greeting, three suggestions, message input with toolbar.',
    components: [{ name: 'AiAssistant', nodeId: '381:1879', variants: 1, properties: [] }] },
  { slug: 'avatar', title: 'Avatar', category: 'display', status: 'Draft', statusNote: PENDING, docs: 'Full specification', built: true, opacityNote: true, related: ['sidebar'],
    purpose: "Circle with the user's initials. Shown on the dark sidebar footer.",
    components: [{ name: 'Avatar', nodeId: '348:907', variants: 1, properties: [t('initials', 'EG')] }] },
  { slug: 'badge', title: 'StatusBadge', category: 'status', status: 'Draft', statusNote: PENDING, docs: 'Full specification', built: true, related: ['count-badge', 'message-banner', 'metric-card'],
    purpose: 'Small rounded label that states a status (Completed, Active, Inherited), a tag (Sub-user · active), a countdown (Expires in 04:47) or a delta (+12%). The label is always text and can be renamed on every instance.',
    components: [{ name: 'StatusBadge', nodeId: '325:849', variants: 24, properties: [v('appearance', 'positive, warning, danger, info, neutral, accent, awaiting, processing'), v('size', 'md, lg, sm'), b('showIcon', false), t('label', 'Status')] }] },
  { slug: 'button', title: 'Button', category: 'actions', status: 'Draft', statusNote: "DRAFT — pending Mary's approval. Screens are not rebuilt yet (Phase 6).", docs: 'Full specification', built: true,
    purpose: 'Text button with an optional leading icon.', related: ['icon-button', 'chip', 'icons', 'spinner'],
    components: [{ name: 'Button', nodeId: '302:835', variants: 96, properties: [v('appearance', 'primary, secondary, tonal, inverse', 'primary'), v('layout', 'default, icon-only', 'default'), v('size', 'md, sm', 'md'), v('state', 'default, disabled, hover, pressed, focus-visible, loading', 'default'), b('showIcon', true), t('label', 'Button')] }] },
  { slug: 'checkbox', title: 'Checkbox', category: 'forms', status: 'Not documented', docs: 'None', built: true, related: ['transactions-grid', 'select-menu', 'icons'],
    components: [{ name: 'Checkbox', nodeId: '522:5090', variants: 3, properties: [v('state', 'unchecked, checked, indeterminate')] }] },
  { slug: 'chip', title: 'Chip', category: 'actions', status: 'Draft', statusNote: PENDING, docs: 'Full specification', built: true, opacityNote: true, related: ['button', 'icon-button', 'ai-assistant'],
    purpose: 'Small translucent pill the user can press: quick-question suggestions and toolbar actions of the AI assistant. Text with an optional icon, or icon only.',
    components: [{ name: 'Chip', nodeId: '344:951', variants: 20, properties: [v('size', 'md, sm'), v('layout', 'default, icon-only'), v('state', 'default, hover, pressed, focus-visible, disabled'), b('showIcon', false), t('label', 'Chip')] }] },
  { slug: 'confirm-payment-modal', title: 'ConfirmPaymentModal', category: 'overlays', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['convert-modal', 'modal-overlay', 'detail-row', 'badge'],
    purpose: 'Modal that asks the user to confirm a 3-D Secure card payment: countdown, amount, payment details, Confirm and Decline.',
    components: [{ name: 'ConfirmPaymentModal', nodeId: '394:2109', variants: 4, properties: [v('type', 'conversion, transfer, withdrawal'), v('state', 'active, expired')] }] },
  { slug: 'convert-modal', title: 'ConvertModal', category: 'overlays', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['confirm-payment-modal', 'modal-overlay', 'spinner', 'icon-tile'],
    purpose: 'Result modal of the currency conversion: spinner while processing, success summary, failure with retry.',
    components: [{ name: 'ConvertModal', nodeId: '394:2113', variants: 9, properties: [v('type', 'conversion, transfer, withdrawal'), v('state', 'processing, success, failed')] }] },
  { slug: 'convert-widget', title: 'ConvertWidget', category: 'widgets', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['dropdown-panel', 'confirm-payment-modal', 'convert-modal'],
    purpose: 'Two-column widget for converting between wallets: form on the left, exchange rate and Confirm on the right.',
    components: [{ name: 'ConvertWidget', nodeId: '381:1429', variants: 1, properties: [] }] },
  { slug: 'count-badge', title: 'CountBadge', category: 'status', status: 'Not documented', docs: 'None', built: true, related: ['button', 'badge'],
    components: [{ name: 'CountBadge', nodeId: '523:5083', variants: 1, properties: [t('count', '3')] }] },
  { slug: 'dashboard-layout', title: 'DashboardLayout', category: 'navigation', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, opacityNote: true, related: ['sidebar', 'page-header', 'section-header'],
    purpose: 'Page structure: canvas background, Sidebar instance and a Content panel (padding 12 / 24, gap 40). Screens are built as frames that follow this structure and fill it with organism instances.',
    components: [{ name: 'DashboardLayout', nodeId: '383:1457', variants: 1, properties: [] }] },
  { slug: 'detail-row', title: 'DetailRow', category: 'display', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['confirm-payment-modal', 'convert-modal'],
    purpose: 'Key-value line in the modal detail cards (Merchant, Card, Verification, Converted, Rate, Fees).',
    components: [{ name: 'DetailRow', nodeId: '393:1890', variants: 1, properties: [t('label', 'Label'), t('value', 'Value')] }] },
  { slug: 'divider', title: 'Divider', category: 'display', status: 'Draft', statusNote: PENDING, docs: 'Full specification', built: true, opacityNote: true, related: ['convert-widget', 'sidebar'],
    purpose: 'One-pixel horizontal line that separates blocks. Fills the width of its container.',
    components: [{ name: 'Divider', nodeId: '342:844', variants: 2, properties: [v('appearance', 'default, inverse')] }] },
  { slug: 'dropdown-panel', title: 'DropdownPanel', category: 'overlays', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['wallet-option', 'convert-widget', 'select-menu'],
    purpose: 'List of wallets to choose from in the Convert widget; the To list also has a group of external destinations.',
    components: [{ name: 'DropdownPanel', nodeId: '396:3158', variants: 2, properties: [v('kind', 'from, to')] }] },
  { slug: 'iban-table', title: 'IbanTable', category: 'tables', status: 'Draft', statusNote: 'DRAFT — created with Mary’s approval 2026-09-25; pending library publish.', docs: 'Composition specification', built: true, related: ['user-row', 'account-details-modal', 'icon-button'],
    purpose: 'Header and row of the IBAN accounts table: Name (link), IBAN with a copy button, Owner, Currency, Balance, Status badge, Top up action.',
    components: [
      { name: 'IbanHeader', nodeId: '496:5131', variants: 1, properties: [] },
      { name: 'IbanRow', nodeId: '500:5175', variants: 2, properties: [v('state', 'default, hover'), t('name', 'Personal'), t('owner', 'Lorem ipsum'), t('currency', 'EUR'), t('balance', '€2.00'), t('iban', 'AA743400000000000000')] }] },
  { slug: 'icon-button', title: 'IconButton', category: 'actions', status: 'Draft', statusNote: PENDING, docs: 'Full specification', built: true, opacityNote: true, related: ['button', 'chip', 'tooltip'],
    purpose: 'Square-touch-target button with only an icon: pagination arrows, profile chevron, exchange arrow, send. One size: 32 px.',
    components: [{ name: 'IconButton', nodeId: '333:906', variants: 20, properties: [v('appearance', 'ghost, tonal, glass, soft'), v('state', 'default, hover, pressed, focus-visible, disabled')] }] },
  { slug: 'icon-tile', title: 'IconTile', category: 'display', status: 'Draft', statusNote: PENDING, docs: 'Full specification', built: true, related: ['metric-card', 'convert-modal', 'icons'],
    purpose: 'Round tile with an icon inside. Static, not a button: metric-card icons (32 px) and status marks in the modals (64 px).',
    components: [{ name: 'IconTile', nodeId: '348:905', variants: 6, properties: [v('appearance', 'neutral, positive, danger'), v('size', 'md, lg')] }] },
  { slug: 'icons', title: 'Icon', category: 'display', status: 'Draft', statusNote: "DRAFT — pending Mary's approval. Screens are not rebuilt yet (Phase 6).", docs: 'Full specification', built: true, related: ['button', 'icon-button', 'icon-tile'],
    purpose: 'One glyph from the Lucide set, sized and coloured only through tokens. Used inside Button, IconButton, StatusBadge, Menu Item and other components.',
    components: [
      { name: 'Icon', nodeId: '292:885', variants: 36, properties: [v('size', 'sm, md, lg', 'sm'), v('color', 'default, muted, strong, primary, accent, inverse, inverse-muted, positive, warning, danger, info, success', 'default'), { name: 'icon', type: 'Instance swap', values: 'Any variant of Lucide icons', default: 'house' }] },
      { name: 'Lucide icons (https://lucide.dev/)', nodeId: '212:1410', variants: 101, properties: [v('icon', '101 glyph names'), v('Property 1', 'lucide, google, apple, svgrepo')] }] },
  { slug: 'input', title: 'Input', category: 'forms', status: 'Draft', statusNote: "DRAFT — pending Mary's approval. The Users screen is not rebuilt yet.", docs: 'Full specification', built: true, opacityNote: true, related: ['select-menu', 'button'],
    purpose: 'Single-line field on a translucent white surface: the search field and the two filter selects (All Statuses, All KYC) of the Users screen. A select is the same field with a trailing chevron.',
    components: [{ name: 'Input', nodeId: '357:969', variants: 11, properties: [v('content', 'placeholder, value'), v('state', 'default, hover, focus, error, disabled, read-only'), b('showLeadingIcon', false), b('showTrailingIcon', true), t('value', 'Value')] }] },
  { slug: 'live-indicator', title: 'LiveIndicator', category: 'status', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['page-header', 'theme-toggle'],
    purpose: 'Small status line that shows data freshness ("Live · Updated 2 min ago").',
    components: [{ name: 'LiveIndicator', nodeId: '381:1344', variants: 1, properties: [] }] },
  { slug: 'message-banner', title: 'MessageBanner', category: 'status', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['confirm-payment-modal', 'badge'],
    purpose: 'Pill with an alert icon and a short message.',
    components: [{ name: 'MessageBanner', nodeId: '393:1960', variants: 1, properties: [t('message', 'Message')] }] },
  { slug: 'metric-card', title: 'MetricCard', category: 'display', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, opacityNote: true, related: ['icon-tile', 'badge', 'dashboard-layout'],
    purpose: 'KPI card: round icon tile, title, optional delta badge, big value.',
    components: [{ name: 'MetricCard', nodeId: '365:995', variants: 1, properties: [t('title', 'Title'), t('value', '0'), b('showDelta', false)] }] },
  { slug: 'modal-overlay', title: 'ModalOverlay', category: 'overlays', status: 'Draft', statusNote: PUBLISH, docs: 'Composition specification', built: true, related: ['confirm-payment-modal', 'convert-modal', 'account-details-modal'],
    purpose: 'Full-screen dimmed layer (scrim) that places one modal window centred, 228 px from the top.',
    components: [{ name: 'ModalOverlay', nodeId: '461:5132', variants: 1, properties: [{ name: 'modal', type: 'Instance swap', values: 'A modal component' }] }] },
  { slug: 'navigation-item', title: 'NavigationItem', category: 'navigation', status: 'Draft', statusNote: "DRAFT — pending Mary's approval. Selected and default are OBSERVED; the other states are APPROVED.", docs: 'Full specification', built: true, opacityNote: true, related: ['sidebar', 'tooltip'],
    purpose: 'One row of the sidebar navigation: icon and page name. The selected page has the purple gradient.',
    components: [{ name: 'NavigationItem', nodeId: '362:905', variants: 6, properties: [v('state', 'default, hover, pressed, selected, focus-visible, disabled'), t('label', 'Home')] }] },
  { slug: 'page-header', title: 'PageHeader', category: 'navigation', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['live-indicator', 'theme-toggle', 'dashboard-layout'],
    purpose: 'Top row of the dashboard: greeting title, data-freshness indicator and light/dark toggle.',
    components: [{ name: 'PageHeader', nodeId: '381:1356', variants: 1, properties: [] }] },
  { slug: 'progress-bar', title: 'ProgressBar', category: 'status', status: 'Draft', statusNote: PENDING, docs: 'Full specification', built: true, related: ['account-card'],
    purpose: 'Horizontal progress bar on the dark account cards: shows how much of the transfer limit is used.',
    components: [{ name: 'ProgressBar', nodeId: '348:963', variants: 1, properties: [] }] },
  { slug: 'section-header', title: 'SectionHeader', category: 'navigation', status: 'Draft', statusNote: 'DRAFT, pending approval.', docs: 'Partial', built: true, related: ['button', 'dashboard-layout'],
    purpose: 'Heading of a dashboard block with two actions.',
    components: [{ name: 'SectionHeader', nodeId: '419:6055', variants: 1, properties: [t('title', 'Accounts')] }] },
  { slug: 'select-menu', title: 'SelectMenu', category: 'forms', status: 'Draft', statusNote: PUBLISH, docs: 'Composition specification', built: true, related: ['input', 'dropdown-panel', 'checkbox'],
    purpose: 'Dropdown list for filter selects: a raised panel with single-choice options, the current choice highlighted with a check.',
    components: [
      { name: 'SelectMenu', nodeId: '481:5178', variants: 2, properties: [v('kind', 'status, kyc')] },
      { name: 'SelectOption', nodeId: '481:5141', variants: 3, properties: [v('state', 'default, hover, selected'), t('label', 'All Statuses')] }] },
  { slug: 'sidebar', title: 'Sidebar', category: 'navigation', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['navigation-item', 'avatar', 'tooltip', 'dashboard-layout'],
    purpose: 'Left navigation column of the product: logo, section titles, NavigationItem rows, profile block.',
    components: [
      { name: 'Sidebar', nodeId: '364:943', variants: 1, properties: [t('userName', 'Emily Gibson'), t('userRole', 'Admin')] },
      { name: 'SidebarCollapsed', nodeId: '645:5029', variants: 1, properties: [] }] },
  { slug: 'spinner', title: 'Spinner', category: 'status', status: 'Draft', statusNote: PENDING, docs: 'Full specification', built: true, related: ['button', 'convert-modal'],
    purpose: 'Circular activity indicator: a 270° purple arc with a gradient. Shows that a request is running.',
    components: [{ name: 'Spinner', nodeId: '348:961', variants: 2, properties: [v('size', 'lg, md')] }] },
  { slug: 'theme-toggle', title: 'ThemeToggle', category: 'forms', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['page-header', 'live-indicator'],
    purpose: 'Segmented control for the colour theme (light / dark).',
    components: [{ name: 'ThemeToggle', nodeId: '381:1330', variants: 1, properties: [] }] },
  { slug: 'tooltip', title: 'Tooltip', category: 'status', status: 'Draft', statusNote: PENDING, docs: 'Partial', built: true, related: ['icon-button', 'convert-widget', 'sidebar'],
    purpose: 'Short one-line hint shown on hover or keyboard focus of a control, for example an icon-only button.',
    components: [{ name: 'Tooltip', nodeId: '592:5083', variants: 1, properties: [t('label', 'Tooltip text')] }] },
  { slug: 'transaction-row', title: 'TransactionRow', category: 'tables', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, opacityNote: true, related: ['transactions-panel', 'badge', 'icon-button'],
    purpose: 'One line of the transactions table (date, user, type, merchant, card, amount, fee, status), its header row and the pagination bar.',
    components: [
      { name: 'TransactionRow', nodeId: '380:1209', variants: 1, properties: [t('date', '07 Sep, 09:14'), t('user', 'Anna K.'), t('type', 'Purchase'), t('merchant', 'Saturn Electronics'), t('card', '•••• 4021'), t('amount', '-84.90 EUR'), t('fee', '0.00 EUR')] },
      { name: 'TransactionsHeader', nodeId: '380:1232', variants: 1, properties: [] },
      { name: 'Pagination', nodeId: '380:1244', variants: 1, properties: [] }] },
  { slug: 'transactions-grid', title: 'transactions-grid', category: 'tables', status: 'Not documented', docs: 'None', built: true, related: ['checkbox', 'badge', 'transaction-row'],
    components: [
      { name: 'TransactionsGridHeader', nodeId: '525:5083', variants: 1, properties: [] },
      { name: 'TransactionsGridRow', nodeId: '525:5175', variants: 3, properties: [v('state', 'default, selected, hover')] }] },
  { slug: 'transactions-panel', title: 'TransactionsPanel', category: 'tables', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, opacityNote: true, related: ['transaction-row', 'transactions-grid', 'dashboard-layout'],
    purpose: 'Table of recent transactions with pagination.',
    components: [{ name: 'TransactionsPanel', nodeId: '381:1527', variants: 1, properties: [] }] },
  { slug: 'user-row', title: 'UserRow', category: 'tables', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['badge', 'button', 'iban-table'],
    purpose: 'One row of the Users table and its header row.',
    components: [
      { name: 'UserRow', nodeId: '388:2403', variants: 1, properties: [t('name', 'Olena Kravchenko'), t('email', 'sample address'), t('accounts', '1'), t('cards', '1'), t('created', 'Sep 12, 2026')] },
      { name: 'UsersHeader', nodeId: '388:2727', variants: 1, properties: [] }] },
  { slug: 'wallet-option', title: 'WalletOption', category: 'overlays', status: 'Draft', statusNote: PENDING, docs: 'Composition specification', built: true, related: ['dropdown-panel', 'select-menu'],
    purpose: 'One row of the dropdown: coin, name, type and balance (WalletOption) or icon with a two-line title (ExternalOption).',
    components: [
      { name: 'WalletOption', nodeId: '396:1894', variants: 3, properties: [v('state', 'default, hover, selected'), t('title', 'USDT (TRC20)'), t('subtitle', 'Crypto wallet'), t('amount', '10,860.00'), b('showCheck', false)] },
      { name: 'ExternalOption', nodeId: '396:1895', variants: 1, properties: [t('title', 'Crypto wallet address'), t('subtitle', 'Send to any external…')] }] },
];

export const componentBySlug = Object.fromEntries(components.map((c) => [c.slug, c]));
