// Generates src/ds/glyphs.generated.ts from tokens/source/figma-glyphs.txt.
// Fails if a glyph that should come from the Lucide package is missing there.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const lucide = createRequire(import.meta.url)('lucide-react');
const pascal = (n) => n.split('-').map((s) => s[0].toUpperCase() + s.slice(1)).join('');
const rows = readFileSync(resolve(root, 'tokens/source/figma-glyphs.txt'), 'utf8').split('\n').map((l) => l.trim()).filter((l) => l && !l.startsWith('#')).map((l) => l.split(/\s+/));
const lucideNames = [], custom = [], origins = {};
for (const [name, origin, flag] of rows) {
  if (flag === 'custom') { custom.push(name); if (origin !== 'lucide') origins[name] = origin; continue; }
  if (!lucide[pascal(name)]) throw new Error(`Glyph "${name}" is not in the lucide-react package. Mark it custom and export its SVG from Figma.`);
  lucideNames.push(name);
}
const out = `// GENERATED by scripts/build-glyphs.mjs from tokens/source/figma-glyphs.txt. Do not edit.
import type { LucideIcon } from 'lucide-react';
import { ${lucideNames.map(pascal).join(', ')} } from 'lucide-react';
export const lucideGlyphs = { ${lucideNames.map((n) => `'${n}': ${pascal(n)}`).join(', ')} } satisfies Record<string, LucideIcon>;
export const customGlyphNames = ${JSON.stringify(custom)} as const;
/** Glyphs whose Figma "Property 1" is not "lucide". */
export const glyphOrigins: Record<string, string> = ${JSON.stringify(origins)};
export const glyphNames = ${JSON.stringify(rows.map((r) => r[0]))} as const;
`;
writeFileSync(resolve(root, 'src/ds/glyphs.generated.ts'), out);
console.log(`glyphs: ${rows.length} (${lucideNames.length} from lucide-react, ${custom.length} custom)`);
